"use client";
import "./globals.css";
import Script from "next/script";
import { Inter } from "next/font/google";
import { Header } from "../src/Header";
import Footer from "../src/Footer";
import { PrimeReactProvider } from "primereact/api";
//theme
import "primereact/resources/themes/lara-light-indigo/theme.css";
//core
import "primereact/resources/primereact.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Samriddhi Frame",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="keywords" />
        <title>Home</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link rel="icon" href="/img/rkInputIcon.png" />
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="/css/style.css" />
        <link rel="stylesheet" type="text/css" href="/css/common.css" />
        <link rel="stylesheet" type="text/css" href="/css/responsive.css" />
        <link rel="stylesheet" href="/css/animate.css" />
        <link rel="stylesheet" type="text/css" href="/css/swiper-bundle.min.css"></link>
      </head>
      <body className={inter.className}>
        <PrimeReactProvider>
          <Header />
          {children}
          <Footer />
        </PrimeReactProvider>
      </body>

      <Script id="scriptAfterInteractive" type="text/javascript" src="/js/jquery.min.js"></Script>
      <Script id="scriptAfterInteractive" type="text/javascript" src="/js/bootstrap.min.js"></Script>
      <Script id="scriptAfterInteractive" type="text/javascript" src="/js/particles.min.js"></Script>
      <Script id="scriptAfterInteractive" type="text/javascript" src="/js/swiper-bundle.min.js"></Script>
      <Script id="scriptAfterInteractive" type="text/javascript" src="/js/custom.js"></Script>
      <Script id="scriptAfterInteractive" type="text/javascript" src="/js/mobile-nav.js"></Script>
      <Script id="scriptAfterInteractive" type="text/javascript" src="/js/wow.js"></Script>
    </html>
  );
}
